<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AttendanceController;
use App\Http\Controllers\Api\AdminController;
use App\Http\Controllers\Api\BudgetController;
use App\Http\Controllers\Api\DirectoryController;
use App\Http\Controllers\Api\PayrollController;
use App\Http\Controllers\Api\StaffController;
use App\Http\Controllers\Api\SystemController;
use App\Http\Controllers\Api\PayrollWriteController;
use App\Http\Controllers\Api\TemplateController;
use App\Http\Controllers\Api\ExportController;
use App\Http\Controllers\Api\MaintenanceController;
use App\Http\Controllers\Api\PerformanceController;
use App\Http\Controllers\Api\ConfigController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\PayslipController;
use App\Http\Controllers\Api\ProjectController;
use App\Http\Controllers\Api\OrgController;
use App\Http\Controllers\Api\MessageController;
use App\Http\Controllers\Api\ApprovalFlowController;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login']);
Route::get('/payslip/query', [PayslipController::class, 'query']);
Route::post('/logout', [AuthController::class, 'logout']);
Route::post('/change-password', [AuthController::class, 'changePassword']);
Route::get('/init', [DirectoryController::class, 'init']);
Route::get('/projects', [DirectoryController::class, 'projects']);
Route::get('/staff', [DirectoryController::class, 'staff']);
Route::get('/attendance', [PayrollController::class, 'attendance']);
Route::get('/attendance/status', [AttendanceController::class, 'status']);
Route::post('/attendance/upload', [AttendanceController::class, 'upload']);
Route::post('/attendance/delete', [AttendanceController::class, 'delete']);
Route::post('/attendance/lock', [AttendanceController::class, 'lock']);
Route::get('/attendance/export', [AttendanceController::class, 'export']);
Route::get('/payroll', [PayrollController::class, 'payroll']);
Route::get('/summary', [PayrollController::class, 'summary']);
Route::post('/payroll/period-coef/save', [PayrollController::class, 'savePeriodCoef']);
Route::get('/payroll/period-coef/list', [PayrollController::class, 'listPeriodCoef']);
Route::get('/payroll/period-coef/pending', [PayrollController::class, 'pendingPeriodCoef']);
Route::post('/payroll/calc', [PayrollWriteController::class, 'calculate']);
Route::post('/payroll/calc-managers', [PayrollWriteController::class, 'calcManagers']);
Route::post('/payroll/calc-case', [PayrollWriteController::class, 'calcCaseStaff']);
Route::post('/payroll/calc-hq', [PayrollWriteController::class, 'calcHq']);
Route::post('/payroll/archive', [PayrollWriteController::class, 'archive']);
Route::post('/payroll/adjust', [PayrollWriteController::class, 'adjust']);
Route::post('/payroll/import-history', [PayrollWriteController::class, 'importHistory']);
Route::get('/payroll/import-history/error-report/{token}', [PayrollWriteController::class, 'errorReport']);
Route::get('/staff/template', [TemplateController::class, 'staff']);
Route::get('/budget/template', [TemplateController::class, 'budget']);
Route::get('/attendance/template', [TemplateController::class, 'attendance']);
Route::get('/payroll/history-template', [TemplateController::class, 'payrollHistory']);
Route::get('/export/project', [ExportController::class, 'project']);
Route::get('/export/managers', [ExportController::class, 'managers']);
Route::get('/export/project-managers', [ExportController::class, 'projectManagers']);
Route::get('/export/case-staff', [ExportController::class, 'caseStaff']);
Route::get('/export/hq-staff', [ExportController::class, 'hqStaff']);
Route::get('/summary/export', [ExportController::class, 'summaryExport']);
Route::get('/export/project-case', [ExportController::class, 'projectCaseStaff']);
Route::get('/export/summary', [ExportController::class, 'summary']);
Route::get('/export/projects_all', [ExportController::class, 'projectsAll']);
Route::get('/export/performance', [ExportController::class, 'performance']);
Route::get('/export/dashboard', [ExportController::class, 'dashboard']);
Route::get('/maintenance/contracts', [MaintenanceController::class, 'contracts']);
Route::post('/maintenance/contracts', [MaintenanceController::class, 'saveContract']);
Route::put('/maintenance/contracts/{id}', [MaintenanceController::class, 'saveContract']);
Route::delete('/maintenance/contracts/{id}', [MaintenanceController::class, 'deleteContract']);
Route::get('/maintenance/partners', [MaintenanceController::class, 'partners']);
Route::post('/maintenance/partners', [MaintenanceController::class, 'savePartner']);
Route::put('/maintenance/partners/{id}', [MaintenanceController::class, 'savePartner']);
Route::delete('/maintenance/partners/{id}', [MaintenanceController::class, 'deletePartner']);
Route::get('/maintenance/contracts/{id}/pdf', [MaintenanceController::class, 'pdf']);
Route::post('/maintenance/contracts/{id}/pdf', [MaintenanceController::class, 'uploadPdf']);
Route::get('/maintenance/dashboard', [MaintenanceController::class, 'dashboard']);
Route::get('/performance/user_options', [PerformanceController::class, 'userOptions']);
Route::get('/performance/leader_approver', [PerformanceController::class, 'leaderApprover']);
Route::get('/performance/plans', [PerformanceController::class, 'list']);
Route::get('/performance/plans/{id}', [PerformanceController::class, 'detail']);
Route::post('/performance/plans/save', [PerformanceController::class, 'save']);
Route::post('/performance/confirm', [PerformanceController::class, 'confirm']);
Route::post('/performance/reject_confirm', fn (\Illuminate\Http\Request $request, PerformanceController $controller) => $controller->reject($request, 'confirm'));
Route::post('/performance/reject_approve', fn (\Illuminate\Http\Request $request, PerformanceController $controller) => $controller->reject($request, 'approve'));
Route::post('/performance/report', [PerformanceController::class, 'report']);
Route::post('/performance/start_report', [PerformanceController::class, 'startReport']);
Route::post('/performance/finish_report', [PerformanceController::class, 'finishReport']);
Route::post('/performance/admin_fill', fn (\Illuminate\Http\Request $request, PerformanceController $controller) => $controller->report($request, true));
Route::post('/performance/urge', [PerformanceController::class, 'urge']);
Route::post('/performance/self_submit', [PerformanceController::class, 'selfSubmit']);
Route::post('/performance/approve', [PerformanceController::class, 'approve']);
Route::post('/performance/delete', [PerformanceController::class, 'delete']);
Route::match(['get', 'post'], '/performance/grade_rules', [PerformanceController::class, 'gradeRules']);
Route::post('/performance/calc', [PerformanceController::class, 'calc']);
Route::get('/performance/export/{id}', [PerformanceController::class, 'export']);
Route::get('/performance/ranking', [PerformanceController::class, 'ranking']);
Route::get('/performance/export_all', [PerformanceController::class, 'exportAll']);
Route::post('/staff/save', [StaffController::class, 'save']);
Route::post('/staff/deduct', [StaffController::class, 'deduct']);
Route::post('/staff/bulk_delete', [StaffController::class, 'bulkDelete']);
Route::post('/staff/bulk_deduct', [StaffController::class, 'bulkDeduct']);
Route::post('/staff/bulk_tax_mode', [StaffController::class, 'bulkTaxMode']);
Route::post('/staff/bulk_upload', [StaffController::class, 'bulkUpload']);
Route::match(['get', 'post'], '/staff/field_config', [StaffController::class, 'fieldConfig']);
Route::post('/projects/save', [ProjectController::class, 'save']);
Route::get('/staff_history', [StaffController::class, 'history']);
Route::get('/salary_adjusts', [StaffController::class, 'adjustments']);
Route::post('/salary_adjust', [StaffController::class, 'salaryAdjust']);
Route::get('/calc_rules', [SystemController::class, 'calcRules']);
Route::get('/symbols', [SystemController::class, 'symbols']);
Route::get('/symbols/formulas', [SystemController::class, 'symbolFormulas']);
Route::get('/symbols/export', [SystemController::class, 'symbolExport']);
Route::get('/settings', [SystemController::class, 'settings']);
Route::get('/payslip/config', [SystemController::class, 'payslipConfig']);
Route::get('/budget', [SystemController::class, 'budget']);
Route::get('/budget/view', [SystemController::class, 'budgetView']);
Route::post('/budget/save', [BudgetController::class, 'save']);
Route::post('/budget/import', [BudgetController::class, 'import']);
Route::get('/users', [AdminController::class, 'users']);
Route::get('/roles', [AdminController::class, 'roles']);
Route::post('/users/save', [AdminController::class, 'saveUser']);
Route::post('/users/status', [AdminController::class, 'setUserStatus']);
Route::post('/roles/save', [AdminController::class, 'saveRoles']);
Route::post('/change_password', [AdminController::class, 'changePassword']);
Route::post('/calc_rules/save', [ConfigController::class, 'saveRules']);
Route::post('/symbols/save', [ConfigController::class, 'saveSymbols']);
Route::post('/symbols/reset', [ConfigController::class, 'resetSymbols']);
Route::post('/symbols/import', [ConfigController::class, 'importSymbols']);
Route::post('/payslip/config/save', [ConfigController::class, 'savePayslip']);
Route::post('/settings/save', [ConfigController::class, 'saveSettings']);
Route::get('/custom_fields', [\App\Http\Controllers\Api\CustomFieldController::class, 'index']);
Route::post('/custom_fields/save', [\App\Http\Controllers\Api\CustomFieldController::class, 'save']);
Route::get('/op_logs', [AdminController::class, 'logs']);
Route::post('/backup', [AdminController::class, 'backup']);
Route::post('/admin/clear-data', [AdminController::class, 'clearData']);
Route::get('/backups', [AdminController::class, 'backups']);
Route::get('/backups/download', [AdminController::class, 'downloadBackup']);
Route::get('/dashboard', [ReportController::class, 'dashboard']);
Route::get('/report/hr', [ReportController::class, 'hrReport']);
Route::get('/report/salary', [ReportController::class, 'salaryReport']);
Route::get('/report/attendance', [ReportController::class, 'attendanceReport']);
Route::get('/staff/export', [ReportController::class, 'staffExport']);
Route::get('/maintenance/fire_report', [MaintenanceController::class, 'fireReport']);
Route::get('/maintenance/elev_report', [MaintenanceController::class, 'elevReport']);
// ---- 组织架构 ----
Route::get('/org/tree', [OrgController::class, 'tree']);
Route::post('/org/node', [OrgController::class, 'createNode']);
Route::post('/org/node/update', [OrgController::class, 'updateNode']);
Route::post('/org/node/move', [OrgController::class, 'moveNode']);
Route::post('/org/node/status', [OrgController::class, 'setStatus']);
Route::post('/org/node/delete', [OrgController::class, 'deleteNode']);
Route::post('/org/migrate', [OrgController::class, 'migrate']);
Route::get('/org/staff', [OrgController::class, 'staffUnder']);
Route::post('/org/staff/move', [OrgController::class, 'moveStaff']);
Route::get('/org/transfer-logs', [OrgController::class, 'transferLogs']);
Route::get('/org/positions', [OrgController::class, 'positions']);
Route::get('/org/staff-options', [OrgController::class, 'staffOptions']);
Route::get('/org/accounts-pending', [OrgController::class, 'accountsPending']);
// ---- 消息通知中心 ----
Route::get('/messages', [MessageController::class, 'list']);
Route::get('/messages/unread_count', [MessageController::class, 'unreadCount']);
Route::post('/messages/read', [MessageController::class, 'markRead']);
Route::post('/messages/read_all', [MessageController::class, 'markAllRead']);
// ---- 通用审批流引擎 ----
Route::get('/approval/positions', [ApprovalFlowController::class, 'positions']);
Route::get('/approval/flows', [ApprovalFlowController::class, 'flows']);
Route::post('/approval/flow_save', [ApprovalFlowController::class, 'flowSave']);
Route::post('/approval/flow_delete', [ApprovalFlowController::class, 'flowDelete']);
Route::post('/approval/flow_toggle', [ApprovalFlowController::class, 'flowToggle']);
Route::get('/approval/flows_public', [ApprovalFlowController::class, 'publicFlows']);
Route::post('/approval/create', [ApprovalFlowController::class, 'create']);
Route::get('/approval/list', [ApprovalFlowController::class, 'list']);
Route::post('/approval/approve', [ApprovalFlowController::class, 'approve']);
Route::post('/approval/reject', [ApprovalFlowController::class, 'reject']);
Route::post('/approval/resubmit', [ApprovalFlowController::class, 'resubmit']);
Route::post('/approval/withdraw', [ApprovalFlowController::class, 'withdraw']);
Route::post('/approval/void', [ApprovalFlowController::class, 'void']);
Route::post('/approval/upload', [ApprovalFlowController::class, 'upload']);
Route::get('/approval/onboard/list', [ApprovalFlowController::class, 'onboardList']);
Route::get('/approval/onboard/{id}', [ApprovalFlowController::class, 'onboardDetail']);
Route::post('/approval/onboard/save', [ApprovalFlowController::class, 'onboardSave']);
Route::post('/approval/onboard/complete', [ApprovalFlowController::class, 'onboardComplete']);
Route::post('/approval/draft_save', [ApprovalFlowController::class, 'draftSave']);
Route::get('/approval/drafts', [ApprovalFlowController::class, 'draftList']);
Route::get('/approval/drafts/{id}', [ApprovalFlowController::class, 'draftDetail']);
Route::post('/approval/draft_delete', [ApprovalFlowController::class, 'draftDelete']);
Route::post('/approval/draft_submit', [ApprovalFlowController::class, 'draftSubmit']);
Route::get('/approval/inbox', [ApprovalFlowController::class, 'inbox']);
Route::post('/approval/inbox_delete', [ApprovalFlowController::class, 'inboxDelete']);
Route::post('/approval/send', [ApprovalFlowController::class, 'send']);
Route::get('/approval/send_targets', [ApprovalFlowController::class, 'sendTargets']);
Route::get('/approval/search', [ApprovalFlowController::class, 'search']);
Route::get('/approval/{id}', [ApprovalFlowController::class, 'detail']);

// ---- 月度采购（整合采购系统）----
Route::any('/purchase/{path?}', [App\Http\Controllers\Api\PurchaseController::class, 'index'])->where('path', '.*');

// ---- 财务管理 ----
Route::any('/finance/{action?}', [App\Http\Controllers\Api\FinanceController::class, 'handle'])->where('action', '[a-zA-Z0-9_/\-]*');

// 钉钉集成
Route::post("/dingtalk/callback", [\App\Http\Controllers\Api\DingtalkCallbackController::class, "handle"]);
Route::get("/dingtalk/status", [\App\Http\Controllers\Api\DingtalkCallbackController::class, "status"]);
Route::get("/dingtalk/config", [\App\Http\Controllers\Api\DingtalkCallbackController::class, "getConfig"]);
Route::post("/dingtalk/config", [\App\Http\Controllers\Api\DingtalkCallbackController::class, "saveConfig"]);
Route::post("/dingtalk/sync-now", [\App\Http\Controllers\Api\DingtalkCallbackController::class, "syncNow"]);
